/**
 * Portfolio Data Query Hooks
 *
 * These hooks provide async data fetching with caching via TanStack Query.
 * Uses the IPC layer which falls back to mock data when not in Tauri.
 */

import {
  useQuery,
  useMutation,
  useQueryClient,
  type UseQueryResult,
  type UseMutationResult,
} from '@tanstack/react-query'
import {
  getDashboardData,
  getHoldings,
  syncPortfolio,
  getEngineHealth,
  getTrueHoldings,
} from '../lib/ipc'
import { useAppStore } from '../store/useAppStore'

// =============================================================================
// Query Hooks
// =============================================================================

/**
 * Fetch engine health status
 * Uses IPC layer (Tauri or mock fallback)
 */
export function useEngineHealth(): UseQueryResult<
  Awaited<ReturnType<typeof getEngineHealth>>,
  Error
> {
  return useQuery({
    queryKey: ['engineHealth'],
    queryFn: getEngineHealth,
    refetchInterval: 30000, // Refetch every 30 seconds
    staleTime: 10000, // Consider stale after 10 seconds
  })
}

/**
 * Fetch dashboard summary data
 * Uses IPC layer (Tauri or mock fallback)
 */
export function useDashboardData(
  portfolioId: number
): UseQueryResult<Awaited<ReturnType<typeof getDashboardData>>, Error> {
  return useQuery({
    queryKey: ['dashboard', portfolioId],
    queryFn: () => getDashboardData(portfolioId),
  })
}

/**
 * Fetch all holdings
 * Uses IPC layer (Tauri or mock fallback)
 */
export function useHoldingsData(
  portfolioId: number
): UseQueryResult<Awaited<ReturnType<typeof getHoldings>>, Error> {
  return useQuery({
    queryKey: ['holdings', portfolioId],
    queryFn: () => getHoldings(portfolioId),
  })
}

/**
 * Fetch X-Ray (look-through) data
 *
 * Note: X-Ray data is global (aggregated across all holdings), not per-portfolio.
 * The backend reads from a shared holdings breakdown file generated by the sync pipeline.
 */
export function useXRayData(): UseQueryResult<Awaited<ReturnType<typeof getTrueHoldings>>, Error> {
  return useQuery({
    queryKey: ['xray'],
    queryFn: getTrueHoldings,
  })
}

// =============================================================================
// Mutation Hooks
// =============================================================================

/**
 * Trigger portfolio sync
 * Uses IPC layer to communicate with Rust/Python backend
 */
export function useSyncPortfolio(): UseMutationResult<
  Awaited<ReturnType<typeof syncPortfolio>>,
  Error,
  { force?: boolean }
> {
  const queryClient = useQueryClient()
  const startSync = useAppStore((state) => state.startSync)
  const completeSync = useAppStore((state) => state.completeSync)
  const failSync = useAppStore((state) => state.failSync)
  const activePortfolioId = useAppStore((state) => state.activePortfolioId)

  return useMutation({
    mutationFn: async ({ force = false }: { force?: boolean } = {}) => {
      startSync()
      return syncPortfolio(activePortfolioId, force)
    },
    onSuccess: () => {
      // If sync completed successfully, it will have syncedPositions > 0
      completeSync()
      // Invalidate all portfolio data queries to refetch fresh data
      queryClient.invalidateQueries({ queryKey: ['dashboard'] })
      queryClient.invalidateQueries({ queryKey: ['holdings'] })
      queryClient.invalidateQueries({ queryKey: ['xray'] })
    },
    onError: (error) => {
      failSync(error instanceof Error ? error.message : 'Unknown error')
    },
  })
}
